name: Trigger Jitpack Build

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jitpack Build
        run: curl "https://jitpack.io/com/github/CloudNetService/cloud-command-framework/main-SNAPSHOT/build.log"